# cmake/build_all.cmake
#
# Builds all Betaflight board configs (or base MCU targets) in parallel.
# Invoke from the repo root:
#
#   cmake -P cmake/build_all.cmake
#
# Optional -D variables:
#   PARALLEL_TARGETS  Simultaneous target builds (default: nproc, max 8)
#   JOBS_PER_TARGET   Compiler jobs per target build (default: 2)
#   BUILD_CONFIGS     ON = board configs (default), OFF = base MCU targets
#   BUILD_DIR         Build output root (default: build/all)
#   TARGETS_FILTER    Semicolon list to limit scope, e.g. "MATEKF405TE;KAKUTEH7"
#   STOP_ON_ERROR     ON to abort on first failure (default: OFF)

cmake_minimum_required(VERSION 3.25)

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
cmake_host_system_information(RESULT _NCPU QUERY NUMBER_OF_PHYSICAL_CORES)
if(NOT _NCPU OR _NCPU LESS 1)
    set(_NCPU 4)
endif()

if(NOT DEFINED PARALLEL_TARGETS)
    set(PARALLEL_TARGETS ${_NCPU})
    if(PARALLEL_TARGETS GREATER 8)
        set(PARALLEL_TARGETS 8)
    endif()
endif()

if(NOT DEFINED JOBS_PER_TARGET)
    set(JOBS_PER_TARGET 2)
endif()

if(NOT DEFINED BUILD_CONFIGS)
    set(BUILD_CONFIGS ON)
endif()

if(NOT DEFINED BUILD_DIR)
    set(BUILD_DIR "${CMAKE_CURRENT_LIST_DIR}/../build/all")
endif()

set(_TOOLCHAIN "${CMAKE_CURRENT_LIST_DIR}/arm-none-eabi-toolchain.cmake")
set(_ROOT      "${CMAKE_CURRENT_LIST_DIR}/..")
cmake_path(NORMAL_PATH _ROOT)
cmake_path(NORMAL_PATH BUILD_DIR)
cmake_path(NORMAL_PATH _TOOLCHAIN)

# Ninja is required for parallel mode
find_program(_NINJA_EXE ninja REQUIRED)

# ---------------------------------------------------------------------------
# Discover targets
# ---------------------------------------------------------------------------
if(BUILD_CONFIGS)
    file(GLOB _HDR_LIST "${_ROOT}/src/config/configs/*/config.h")
    if(NOT _HDR_LIST)
        message(FATAL_ERROR
            "No board configs found under src/config/configs/.\n"
            "Hydrate the submodule: git submodule update --init src/config")
    endif()
    set(_BUILD_TYPE "config")
    set(_BF_ARG_PREFIX "-DBF_CONFIG=")
    set(_ITEMS "")
    foreach(_hdr ${_HDR_LIST})
        get_filename_component(_dir "${_hdr}" DIRECTORY)
        get_filename_component(_name "${_dir}" NAME)
        list(APPEND _ITEMS "${_name}")
    endforeach()
else()
    file(GLOB_RECURSE _MK_LIST "${_ROOT}/src/platform/*/target/*/target.mk")
    set(_BUILD_TYPE "target")
    set(_BF_ARG_PREFIX "-DBF_TARGET=")
    set(_ITEMS "")
    foreach(_mk ${_MK_LIST})
        get_filename_component(_dir "${_mk}" DIRECTORY)
        get_filename_component(_name "${_dir}" NAME)
        list(APPEND _ITEMS "${_name}")
    endforeach()
endif()

list(SORT _ITEMS)

if(TARGETS_FILTER)
    set(_FILTERED "")
    foreach(_item ${_ITEMS})
        if(_item IN_LIST TARGETS_FILTER)
            list(APPEND _FILTERED "${_item}")
        endif()
    endforeach()
    set(_ITEMS "${_FILTERED}")
endif()

list(LENGTH _ITEMS _TOTAL)
message(STATUS "Building ${_TOTAL} ${_BUILD_TYPE}(s)")
message(STATUS "  Parallel targets : ${PARALLEL_TARGETS}")
message(STATUS "  Jobs per target  : ${JOBS_PER_TARGET}")
message(STATUS "  Build dir        : ${BUILD_DIR}")
message(STATUS "")

# ---------------------------------------------------------------------------
# Generate a Ninja file — one rule per target, parallelism via ninja -j N
#
# Stamp files live in <BUILD_DIR>/.stamps/ (relative paths = no Windows
# drive-letter colon issues in Ninja's build-output fields).
# ---------------------------------------------------------------------------
set(_STAMP_DIR "${BUILD_DIR}/.stamps")
file(MAKE_DIRECTORY "${_STAMP_DIR}")

# Write a small per-target cmake script so we avoid shell && quoting issues.
# cmake -P <script> does configure + build, then touches the stamp on success.
set(_SCRIPTS_DIR "${BUILD_DIR}/.scripts")
file(MAKE_DIRECTORY "${_SCRIPTS_DIR}")

foreach(_item ${_ITEMS})
    set(_bdir  "${BUILD_DIR}/${_item}")
    set(_stamp "${_STAMP_DIR}/${_item}")
    set(_script "${_SCRIPTS_DIR}/${_item}.cmake")
    set(_log    "${_bdir}/build_all.log")

    file(WRITE "${_script}"
"# Auto-generated by cmake/build_all.cmake — do not edit
set(BF_ARG \"${_BF_ARG_PREFIX}${_item}\")
set(BDIR    \"${_bdir}\")
set(STAMP   \"${_stamp}\")
set(LOG     \"${_log}\")

file(MAKE_DIRECTORY \"\${BDIR}\")

execute_process(
    COMMAND \"${CMAKE_COMMAND}\"
        -S \"${_ROOT}\"
        -B \"\${BDIR}\"
        \"-DCMAKE_TOOLCHAIN_FILE=${_TOOLCHAIN}\"
        \"\${BF_ARG}\"
        -GNinja
    RESULT_VARIABLE _r
    OUTPUT_FILE \"\${LOG}\"
    ERROR_FILE  \"\${LOG}\"
)
if(NOT _r EQUAL 0)
    message(FATAL_ERROR \"Configure failed for ${_item} — see \${LOG}\")
endif()

execute_process(
    COMMAND \"${CMAKE_COMMAND}\" --build \"\${BDIR}\" -- -j${JOBS_PER_TARGET}
    RESULT_VARIABLE _r
    OUTPUT_FILE \"\${LOG}\"
    ERROR_FILE  \"\${LOG}\"
)
if(NOT _r EQUAL 0)
    message(FATAL_ERROR \"Build failed for ${_item} — see \${LOG}\")
endif()

file(TOUCH \"\${STAMP}\")
message(STATUS \"OK  ${_item}\")
")
endforeach()

# Build the Ninja file
set(_NF "")

# Global rule: run cmake -P on a per-target script
string(APPEND _NF "cmake_exe = ${CMAKE_COMMAND}\n\n")
string(APPEND _NF "rule bf\n")
string(APPEND _NF "  command = $cmake_exe -P $script\n")
string(APPEND _NF "  description = [$target]\n\n")

foreach(_item ${_ITEMS})
    # Ninja output path must be relative (avoids Windows drive-letter colon)
    string(APPEND _NF "build .stamps/${_item}: bf\n")
    string(APPEND _NF "  script = ${_SCRIPTS_DIR}/${_item}.cmake\n")
    string(APPEND _NF "  target = ${_item}\n\n")
endforeach()

# Default target builds everything
set(_all "")
foreach(_item ${_ITEMS})
    string(APPEND _all " .stamps/${_item}")
endforeach()
string(APPEND _NF "build all: phony${_all}\n")
string(APPEND _NF "default all\n")

set(_NINJA_FILE "${BUILD_DIR}/build_all.ninja")
file(WRITE "${_NINJA_FILE}" "${_NF}")

# ---------------------------------------------------------------------------
# Run Ninja
# ---------------------------------------------------------------------------
message(STATUS "Starting parallel build ...")
message(STATUS "Per-target logs: ${BUILD_DIR}/<target>/build_all.log")
message(STATUS "")

execute_process(
    COMMAND "${_NINJA_EXE}" -j${PARALLEL_TARGETS} -f "${_NINJA_FILE}" -C "${BUILD_DIR}"
    WORKING_DIRECTORY "${BUILD_DIR}"
    RESULT_VARIABLE _BLD_RET
)

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
set(_PASSED "")
set(_FAILED "")
foreach(_item ${_ITEMS})
    if(EXISTS "${_STAMP_DIR}/${_item}")
        list(APPEND _PASSED "${_item}")
    else()
        list(APPEND _FAILED "${_item}")
    endif()
endforeach()

list(LENGTH _PASSED _N_PASS)
list(LENGTH _FAILED _N_FAIL)

message(STATUS "")
message(STATUS "========================================")
message(STATUS "Build summary: ${_N_PASS} passed, ${_N_FAIL} failed / ${_TOTAL} total")
if(_FAILED)
    message(STATUS "Failed targets:")
    foreach(_f ${_FAILED})
        message(STATUS "  FAIL  ${_f}  →  ${BUILD_DIR}/${_f}/build_all.log")
    endforeach()
endif()
message(STATUS "========================================")

if(_BLD_RET AND NOT _BLD_RET EQUAL 0)
    message(SEND_ERROR "Build finished with failures.")
endif()
